[2023-11-02T09:32:25.365-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: economics_data_pipeline.pull_and_save_fred_data manual__2023-11-02T14:27:08.088916+00:00 [queued]>
[2023-11-02T09:32:25.368-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: economics_data_pipeline.pull_and_save_fred_data manual__2023-11-02T14:27:08.088916+00:00 [queued]>
[2023-11-02T09:32:25.368-0500] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-02T09:32:25.374-0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): pull_and_save_fred_data> on 2023-11-02 14:27:08.088916+00:00
[2023-11-02T09:32:25.380-0500] {standard_task_runner.py:57} INFO - Started process 96095 to run task
[2023-11-02T09:32:25.387-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'economics_data_pipeline', 'pull_and_save_fred_data', 'manual__2023-11-02T14:27:08.088916+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/economics_data_pipe.py', '--cfg-path', '/var/folders/3l/sjtljk5j23ng0k_w12x41kh80000gn/T/tmp22alt9i8']
[2023-11-02T09:32:25.388-0500] {standard_task_runner.py:85} INFO - Job 20: Subtask pull_and_save_fred_data
[2023-11-02T09:32:25.422-0500] {task_command.py:416} INFO - Running <TaskInstance: economics_data_pipeline.pull_and_save_fred_data manual__2023-11-02T14:27:08.088916+00:00 [running]> on host macbook-pro-207.local
[2023-11-02T09:32:25.459-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='hermesadmin' AIRFLOW_CTX_DAG_ID='economics_data_pipeline' AIRFLOW_CTX_TASK_ID='pull_and_save_fred_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T14:27:08.088916+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-02T14:27:08.088916+00:00'
[2023-11-02T09:32:25.462-0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/dimz/EconWizard/airflow/dags/economics_data_pipe.py", line 29, in pull_and_save_fred_data
    airflow_home = Variable.get("AIRFLOW_HOME")
  File "/Users/dimz/EconWizard/hermesvirtual/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable AIRFLOW_HOME does not exist'
[2023-11-02T09:32:25.466-0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=economics_data_pipeline, task_id=pull_and_save_fred_data, execution_date=20231102T142708, start_date=20231102T143225, end_date=20231102T143225
[2023-11-02T09:32:25.471-0500] {standard_task_runner.py:104} ERROR - Failed to execute job 20 for task pull_and_save_fred_data ('Variable AIRFLOW_HOME does not exist'; 96095)
[2023-11-02T09:32:25.490-0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-02T09:32:25.500-0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
